name: Dependency Review
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.png'
      - '**/*.jpg'
  workflow_dispatch:
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          fail-on-severity: critical

